local_backend: true 

backend: # The two following lines need to be indented
  name: git-gateway # The authentication method we use for Netlify CMS
  branch: main # Branch to update when we push our content (it can be any branch in our repo)

# Do not indent these lines
media_folder: "/uploads" # Exact path where we store the uploaded media
public_folder: "/uploads" # We do not need to specify the /public part as all the files from it are stored in the root directory after the build step
publish_mode: editorial_workflow

site_url: https://effulgent-speculoos-a84be1.netlify.app
display_url: https://effulgent-speculoos-a84be1.netlify.app

logo_url: /favicon.png

collections:
  - label: About # Label used in the UI for the collection
    label_singular: Section # Label for singular post
    name: about # Name of the collection used for various functionality in the CMS
    folder: /src/components/about # Where each new post with .md should be saved
    create: true # Allows users to create new items in the collection
    fields:
      - { label: "Emphasized Text", name: "emphasis", widget: "markdown" } # Field Description
      - { label: "Rest of Description", name: "description", widget: "markdown" } # Field Description

  - label: Team # Label used in the UI for the collection
    label_singular: Section # Label for singular post
    name: team # Name of the collection used for various functionality in the CMS
    folder: /src/components/team # Where each new post with .md should be saved
    create: true # Allows users to create new items in the collection
    slug: {{Name}}
    fields:
      - { label: "Name", name: "name", widget: "string" } # Field Title
      - { label: "Role", name: "role", widget: "string" } # Field Title     
      - { label: "Bio", name: "bio", widget: "markdown" } # Field Description
      - { label: "Headshot", name: "headshot", widget: "image" } # Field Featured Image